name: CD Workflow

on:
  push:
    branches:
      - main

jobs:
  cd-deploy-test:
    name: Deploy to TEST
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Databricks CLI + Dependencies
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          pip install --upgrade pip setuptools wheel

      - name: Configure Databricks (TEST)
        run: |
          cat <<EOF > ~/.databrickscfg
[TEST]
host = https://3529659471634240.0.gcp.databricks.com
token = ${{ secrets.DATABRICKS_TEST_TOKEN }}
EOF

      - name: Deploy to TEST
        run: |
          databricks bundle deploy \
            --target test \
            --profile TEST

  cd-deploy-prod:
    name: Deploy to PROD
    needs: cd-deploy-test
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Databricks CLI + Dependencies
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          pip install --upgrade pip setuptools wheel

      - name: Configure Databricks (PROD)
        run: |
          cat <<EOF > ~/.databrickscfg
[PROD]
host = https://2815004578763257.7.gcp.databricks.com
token = ${{ secrets.DATABRICKS_PROD_TOKEN }}
EOF

      - name: Deploy to PROD
        run: |
          databricks bundle deploy \
            --target prod \
            --profile PROD
